FROM maven:3.6.1-jdk-11-slim AS builder

COPY . /src
WORKDIR /src
RUN mvn package
RUN ls /src/target

FROM resin/raspberry-pi-openjdk
COPY --from=builder /src/target /apps
COPY application.properties /apps/application.properties

WORKDIR /apps
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "apiPhoto-null.jar", "--spring.config.location=file:/apps/application.properties"]
